# Generated by Django 2.2.5 on 2019-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
